volumes:
  grafana-data: {}


networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1

services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    command: -conf /etc/coredns/Corefile
    sysctls:
    - "net.ipv4.ip_unprivileged_port_start=0"
    ports:
      - "5353:53"
      - "5353:53/udp"
      - "9253:9253" # Prometheus
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile
    networks:
      backend:
        ipv4_address: 10.10.1.20

  named-caching:
    build:
      context: ./named
      dockerfile: Dockerfile
    image: named-dnstap:latest
    container_name: named-caching
    ports:
      - "5153:53"
      - "5153:53/udp"
    volumes:
      - ./named/logging.conf:/etc/named/logging.conf
      - ./named/named-caching.conf:/etc/named/named.conf
      - ./named/vector.yaml:/etc/vector/vector.yaml
    networks:
      backend:
        ipv4_address: 10.10.1.22
    depends_on:
      - vector

  named-authoritative:
    build:
      context: ./named
      dockerfile: Dockerfile
    image: named-dnstap:latest
    container_name: named-authoritative
    ports:
      - "5253:53"
      - "5253:53/udp"
    volumes:
      - ./named/logging.conf:/etc/named/logging.conf
      - ./named/named-authoritative.conf:/etc/named/named.conf
      - ./named/var/db.example.com:/var/named/db.example.com
      - ./named/var/db.root:/var/named/db.root
    networks:
      backend:
        ipv4_address: 10.10.1.21
    depends_on:
      - vector

  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 10.10.1.40

    volumes:
      - ./vector:/etc/vector:ro
    ports:
      - "9000:9000"
      - "9053:9053"
      - "8686:8686"
    depends_on:
      - coredns
      - loki
      - mimir

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - 3101:3100
    volumes:
      - ./loki/loki.yaml:/etc/loki/config.yaml
      - ./data:/data
    networks: 
      backend:
        ipv4_address: 10.10.1.30

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - 9090:9090
    restart: unless-stopped
    command: --config.file=/etc/mimir.yaml
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
      - ./mimir/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml
    networks:
      backend:
        ipv4_address: 10.10.1.31
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
            jsonData:
              httpHeaderName1: "X-Scope-OrgID"
            secureJsonData:
              httpHeaderValue1: "tenant1"
          - name: Mimir
            type: prometheus
            access: proxy
            orgId: 1
            url: http://mimir:9090/prometheus
            basicAuth: false
            isDefault: false
            version: 1
            editable: false
        EOF
        mkdir -p /etc/grafana/provisioning/dashboards
        cat <<EOF > /etc/grafana/provisioning/dashboards/dashboards.yaml
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards
        EOF
        /run.sh
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:
        ipv4_address: 10.10.1.32
  trafficgen:
    build:
      context: ./trafficgen
      dockerfile: Dockerfile
    image: trafficgen:latest
    container_name: trafficgen
    environment:
      - NAMESERVER=10.10.1.20
    networks:
      backend:
        ipv4_address: 10.10.1.33
    depends_on:
      - coredns